### PR TITLE
feat: add a search bar on the main page

### PR DESCRIPTION
**Pull request by Tanguy-Boisset**
Adds a search bar on the main page to find controls more easily.

demo2

### CODE REVIEW

**Comment by thomas-girard** [comment]
image
small CSS bug

**Comment by Tanguy-Boisset** [comment]
I need to investigate as I did not have this bug during my testing. I may have an idea where this comes from though.

**Comment by thomas-girard** [comment]
image
another small bug : the search bar is is closed, but the content is not

**Review by jmbesnard — DISMISSED** [review]

**Comment by Tanguy-Boisset** [comment]
I fixed the second bug but I can't reproduce the first one at all...

**Review by jmbesnard — APPROVED** [review]

**Review by thomas-girard — APPROVED** [review]

**Pull request merged**
