### PR TITLE
Fix crash in GPO with special character

### PR DESCRIPTION
**Pull request by laxa**
When a GPO contains a special character in its name (such as "/"), the report generations fails. For example:

```
[+]Generating path to unconstrained 2nd phase ????
Traceback (most recent call last):
  File "/home/laxa/.local/bin/AD-miner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/laxa/.local/pipx/venvs/ad-miner/lib/python3.11/site-packages/ad_miner/__main__.py", line 154, in main
    domains = Domains(arguments, neo4j)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laxa/.local/pipx/venvs/ad-miner/lib/python3.11/site-packages/ad_miner/sources/modules/domains.py", line 241, in __init__
    self.get_unpriv_users_to_GPO()
  File "/home/laxa/.local/pipx/venvs/ad-miner/lib/python3.11/site-packages/ad_miner/sources/modules/domains.py", line 1562, in get_unpriv_users_to_GPO
    page_left_graph.render()
  File "/home/laxa/.local/pipx/venvs/ad-miner/lib/python3.11/site-packages/ad_miner/sources/modules/page_class.py", line 38, in render
    with open(
         ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './render_domain/html/users_GPO_RANDOMSTRING/U@DOMAIN.LOCAL-left-graph.html'
```

This PR fix the crash by replacing the directory seperator by an underscore character. This is potentially an incomplete fix as other characters might trigger the same crash depending on the operating system.

### CODE REVIEW

**Comment by jmbesnard** [comment]
Hi.

Thanks for spotting this and proposing a fix. I never came accross GPO containing "/" !

Your ".replace" will work just fine to be able to write the html file.
However, you'd need to do the same to generated links (and there are quite a few).

You'd also need to consider the case when --gpo_deep flag is being used (which is an option to perform this control from a different perspective).

**Comment by thomas-girard** [comment]
Hi, 

I have fixed the issue in this PR https://github.com/Mazars-Tech/AD_Miner/pull/19 by encoding all the URL links. Can you confirm if this effectively resolves your problem 😉 ?

Thanks

Thomas

**Comment by laxa** [comment]
Encoding characters in the URL will not solve the root problem which is the '/' character messing around when creating files. I have not tried fixing all links yet but the simplest solution would be to rename GPO with bad characters from scratch.
Encoding will probably fix issues with bad character that I have not encountered yet.

**Comment by laxa** [comment]
Well, the #19 will not be enough, links are correctly quoted but are pointing to not existing files. So here are the possibilities that I can think of to fix the issue

- Rename impacted GPO to remote special characters (only slash so far), but this could induce bad comprehension when browsing the UI
- Rework the generation of files to use the object_id of GPO as identifier rather than the GPO's name, this would avoid problem with special characters. This solution seems the best because no modification of name is performed but this might requires lots of work.

Let me know what you think. I might be able to do the first proposition by modifying the #19 and replacing slash characters before quoting the links.
If you choose the latter proposition, I am not sure I have the will to dive that deep into the project.

**Comment by laxa** [comment]
The PR has been updated and should fix this issue. I have only modified the generation of links regarding GPO. The switch `--gpo_deep` does not impact this issue as far as I have tested. The name displayed contains correctly the slash but not the links.
I have included the #19 into the fix for the simplicity.

**Comment by thomas-girard** [comment]
Hi laxa, 
Than you for your PR, it works
image

**Review by thomas-girard — APPROVED** [review]

**Review by Tanguy-Boisset — APPROVED** [review]
Looks good to me. Thanks a lot for your contribution !

**Pull request merged**
